# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import mensaje_pb2 as mensaje__pb2


class AutenticadorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Autenticar = channel.unary_unary(
                '/mensajes.Autenticador/Autenticar',
                request_serializer=mensaje__pb2.AuthenticationRequest.SerializeToString,
                response_deserializer=mensaje__pb2.AuthenticationReply.FromString,
                )


class AutenticadorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Autenticar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AutenticadorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Autenticar': grpc.unary_unary_rpc_method_handler(
                    servicer.Autenticar,
                    request_deserializer=mensaje__pb2.AuthenticationRequest.FromString,
                    response_serializer=mensaje__pb2.AuthenticationReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mensajes.Autenticador', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Autenticador(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Autenticar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensajes.Autenticador/Autenticar',
            mensaje__pb2.AuthenticationRequest.SerializeToString,
            mensaje__pb2.AuthenticationReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class MensajeriaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ObtenerBandejaEntrada = channel.unary_unary(
                '/mensajes.Mensajeria/ObtenerBandejaEntrada',
                request_serializer=mensaje__pb2.UserRequest.SerializeToString,
                response_deserializer=mensaje__pb2.BandejaReply.FromString,
                )
        self.ObtenerBandejaSalida = channel.unary_unary(
                '/mensajes.Mensajeria/ObtenerBandejaSalida',
                request_serializer=mensaje__pb2.UserRequest.SerializeToString,
                response_deserializer=mensaje__pb2.BandejaReply.FromString,
                )
        self.EnviarCorreo = channel.unary_unary(
                '/mensajes.Mensajeria/EnviarCorreo',
                request_serializer=mensaje__pb2.CorreoNuevo.SerializeToString,
                response_deserializer=mensaje__pb2.EnviarCorreoReply.FromString,
                )
        self.EliminarCorreo = channel.unary_unary(
                '/mensajes.Mensajeria/EliminarCorreo',
                request_serializer=mensaje__pb2.EliminarRequest.SerializeToString,
                response_deserializer=mensaje__pb2.OperacionReply.FromString,
                )
        self.Leido = channel.unary_unary(
                '/mensajes.Mensajeria/Leido',
                request_serializer=mensaje__pb2.LeidoRequest.SerializeToString,
                response_deserializer=mensaje__pb2.OperacionReply.FromString,
                )


class MensajeriaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ObtenerBandejaEntrada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerBandejaSalida(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarCorreo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarCorreo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Leido(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MensajeriaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ObtenerBandejaEntrada': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerBandejaEntrada,
                    request_deserializer=mensaje__pb2.UserRequest.FromString,
                    response_serializer=mensaje__pb2.BandejaReply.SerializeToString,
            ),
            'ObtenerBandejaSalida': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerBandejaSalida,
                    request_deserializer=mensaje__pb2.UserRequest.FromString,
                    response_serializer=mensaje__pb2.BandejaReply.SerializeToString,
            ),
            'EnviarCorreo': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarCorreo,
                    request_deserializer=mensaje__pb2.CorreoNuevo.FromString,
                    response_serializer=mensaje__pb2.EnviarCorreoReply.SerializeToString,
            ),
            'EliminarCorreo': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarCorreo,
                    request_deserializer=mensaje__pb2.EliminarRequest.FromString,
                    response_serializer=mensaje__pb2.OperacionReply.SerializeToString,
            ),
            'Leido': grpc.unary_unary_rpc_method_handler(
                    servicer.Leido,
                    request_deserializer=mensaje__pb2.LeidoRequest.FromString,
                    response_serializer=mensaje__pb2.OperacionReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mensajes.Mensajeria', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Mensajeria(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ObtenerBandejaEntrada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensajes.Mensajeria/ObtenerBandejaEntrada',
            mensaje__pb2.UserRequest.SerializeToString,
            mensaje__pb2.BandejaReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ObtenerBandejaSalida(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensajes.Mensajeria/ObtenerBandejaSalida',
            mensaje__pb2.UserRequest.SerializeToString,
            mensaje__pb2.BandejaReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EnviarCorreo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensajes.Mensajeria/EnviarCorreo',
            mensaje__pb2.CorreoNuevo.SerializeToString,
            mensaje__pb2.EnviarCorreoReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EliminarCorreo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensajes.Mensajeria/EliminarCorreo',
            mensaje__pb2.EliminarRequest.SerializeToString,
            mensaje__pb2.OperacionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Leido(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mensajes.Mensajeria/Leido',
            mensaje__pb2.LeidoRequest.SerializeToString,
            mensaje__pb2.OperacionReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
